# Generated by Django 6.1 on 2026-08-14 07:58

import travelApp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0006_booking_tour_alter_contact_id_alter_destination_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=travelApp.models.DestinationImageField(max_length=255, verbose_name='image'),
        ),
    ]
