# Generated by Django 6.1 on 2026-08-14 08:41

import travello.models
from django.db import migrations, models


def move_existing_destinations_to_index(apps, schema_editor):
    old_destinations = apps.get_model('travello', 'Destination')
    index_destinations = apps.get_model('travello', 'IndexDestination')
    for destination in old_destinations.objects.all().iterator():
        index_destinations.objects.create(
            id=destination.id,
            name=destination.name,
            img=destination.img,
            desc=destination.desc,
            price=destination.price,
            offer=destination.offer,
        )
    old_destinations.objects.all().delete()


def restore_existing_destinations(apps, schema_editor):
    old_destinations = apps.get_model('travello', 'Destination')
    index_destinations = apps.get_model('travello', 'IndexDestination')
    for destination in index_destinations.objects.all().iterator():
        old_destinations.objects.create(
            id=destination.id,
            name=destination.name,
            img=destination.img,
            desc=destination.desc,
            price=destination.price,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_alter_destination_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', travello.models.DestinationImageField(max_length=255, verbose_name='image')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
            ],
            bases=(travello.models.DestinationImageMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
        migrations.AddField(
            model_name='destination',
            name='key_provisions',
            field=models.TextField(default='', help_text='Enter one key provision per line.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='subheading',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.RunPython(move_existing_destinations_to_index, restore_existing_destinations),
    ]
