# Generated by Django 6.1 on 2026-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0008_indexdestination_remove_destination_offer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ('display_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='indexdestination',
            options={'ordering': ('display_order', 'id')},
        ),
        migrations.AddField(
            model_name='destination',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Ties use the original ID order.'),
        ),
        migrations.AddField(
            model_name='indexdestination',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Ties use the original ID order.'),
        ),
    ]
