# Generated by Django 6.1 on 2026-08-14 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0010_backfill_destination_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelApp.tour'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travelApp.booking'),
        ),
    ]
