# Generated by Django 6.1 on 2026-09-14 08:07

import travelApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0011_alter_booking_tour_alter_payment_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', travelApp.models.GalleryImageField(max_length=255, verbose_name='media file')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('caption', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Ties use the original ID order.')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
