# Generated by Django 6.1 on 2026-09-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0012_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_location', models.CharField(max_length=200)),
                ('visit_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('budget_range', models.CharField(choices=[('under_100', 'Under $100 per person'), ('100_250', '$100–$250 per person'), ('250_500', '$250–$500 per person'), ('500_plus', 'Over $500 per person'), ('flexible', 'Flexible / discuss with us')], max_length=20)),
                ('preferred_services', models.TextField(blank=True)),
                ('additional_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'booking inquiry',
                'verbose_name_plural': 'booking inquiries',
                'ordering': ('-created_at',),
            },
        ),
    ]
