# Generated by Django 5.2.7 on 2025-11-05 12:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_contact_options_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
