# Generated by Django 6.1 on 2026-08-14 09:01

from django.db import migrations


def assign_missing_orders(apps, schema_editor):
    for model_name in ('IndexDestination', 'Destination'):
        model = apps.get_model('travello', model_name)
        highest = model.objects.order_by('-display_order', '-id').values_list('display_order', flat=True).first() or 0
        missing = model.objects.filter(display_order=0).order_by('id')
        for destination in missing:
            highest += 1
            model.objects.filter(pk=destination.pk).update(display_order=highest)


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_missing_orders, migrations.RunPython.noop),
    ]
